int.go
logger_test.go

Sub-loggers were only having their name set if the parent logger had a name. This patch fixes that and adds some tests to boot.

Fix sub-logger name prefixing

---

int.go
log.go

This is a proposed fix for #11 
In the event that your project does _not_ use hclog, however you wish to generate an hclog logger for a particular subsystem, it is useful to share a writer. This change exposes a configurable mutex to go along with the configured writer. If not set, hclog will generate and consume its own mutex.
One other option is to allow hclog to take in a stdlib logger and wrap around it, kicking back an hclog logger, however the output would then be subject to the formatting of the original logger, and would result in a much larger patch. I'm happy to take this route, however, if it makes more sense.

[#11] Expose a configurable mutex for shared writers

---

int.go
logger_test.go

During the Vault migration to hclog log we ran into a data race error. This was traced back to a couple of slice aliasing instances in hclog. Tests were written (first commit) demonstrating the coupling between separate loggers. These operations in goroutines will trigger race detector errors (as well as incorrect output).
It was also discovered that the bound `With()` parameters were not being output if the format is set to JSON.
Both of these issues are addressed in this PR.

With() fixes

---

README.md
int.go
log.go
logger_test.go

A common complaint about hclog is that it doesn't do Sprintf logging at all, which makes it a bit more combersome that other loggers. This change bridges that gap by allowing code like:
```
logger.Info("detected new production information", "production", hclog.Fmt("%d beans/day", beansPerDay))
```

Add hclog.Fmt to make it easier when doing string formatting

---

int.go
logger_test.go

I understand the desire to have things aligned vertically, but adding the space inside the bracket makes grepping challenging. I moved the space outside the bracket, which will give the same behavior, but also look less weird (in my humble opinion).

Add space after bracket

---

int.go
logger_test.go

Rather than render slices via Sprintf, this renders them out exactly using a more JSON-like syntax. Nested slices are still rendered with Sprintf though.
Example:
```
logger.Info("this is test", "who", "programmer", "why", []interface{}{"testing", "dev", 1, uint64(5), []int{3, 4}})
```
would output
```
[INFO]  test: this is test: who=programmer why=[testing, dev, 1, 5, "[3 4]"]
```

Improve rendering of slice values

---

README.md
int.go
log.go
nulllogger.go

This makes it possible to reconfigure the global logger, particularly useful when other libraries already use it.  I added an example to the end of the readme.

Expose Writer to allow for configuring standard logger

---

global.go
intlogger.go
logger.go
nulllogger.go
nulllogger_test.go
stacktrace.go
stdlog.go

Probably 95% of this commit only updates comments so my linters don’t complain sbout them anymore.
The other 5% does some very, very mild refactoring of the internal logger to make it easier to read the code.
Functionally it doesn’t change anything and it (of course) doesn’t change the public API!

Fix comments to silence linters

---

intlogger.go
logger.go
logger_test.go
writer.go

The `LevelWriter` interface extends the default `io.Writer` Write function with a `level` parameter:
```go
LevelWrite(level Level, p []byte) error
```
This allows the writer to write log messages to different targets based on the given log level.

Add a LevelWriter interface to use as leveled writer

---

intlogger.go
logger_test.go

Handle cases where json logging fails to write:
* json serialization errors; log plain message with
metadata with a field indicating that args are omitted from logs
* io errors: ignore them, the same as non-json logging
Panicing in either case is somewhat unexpected and lead to unexpected
crashes, that can escalate  a minor bad untested logging into an process
crashes.
Fixes https://github.com/hashicorp/go-hclog/issues/38

Don't panic if json logging fails

---

intlogger.go
logger.go
stdlog.go
stdlog_test.go

Allow forcing the log level when using the standard logger. This is
useful for scenarios when the caller of the standard logger will only
ever emit logs at a known level. An example of this is in the stdlib
with the HTTP reverse proxy:
https://golang.org/src/net/http/httputil/reverseproxy.go?s=1370:1578

Allow Standard Logger to force log level

---

context.go
context_test.go

WithContext also supports additional arguments to set fields since this
is a very common operation.
One question @evanphx: should `FromContext` return `L()` if no logger is found? That would avoid a nil-check, but I'm not sure if that's the right behavior. For now I return nil.

{From,With}Context for storing a logger in a context.Context

---

interceptlogger.go
interceptlogger_test.go
logger.go

Creates StandardLoggerIntercept and StandardWriterIntercept so that
Intercepting loggers can create StandardLoggers and maintain the ability
to write to registered sinks

Add interface to allow StandardLoggers to also log

---

interceptlogger_test.go
intlogger.go
logger_test.go

First check if initial offset is inside a logger implementation file (interceptlogger.go, intlogger.go) if it is, increase the offset by 1

Adjust runtime caller offset if necessary

---

README.md

[Logger](https://godoc.org/github.com/hashicorp/go-hclog#Logger) does not export a `Writer` function, but instead a `StandardWriter`.

Fix README example of using hclog with log

---

interceptlogger.go

The old code would copy the mutex into sub-loggers, which is a big no-no.

Fix sharing the mutex between created loggers properly

---

go.sum
intlogger.go
logger_test.go

Prior to this, passing an uneven number of args would cause the passed value to be treated like a key, which had to be a string, which it probably wasn't.
So this makes it so if you pass an uneven number of args, it assumes the orphan is actually an orphan value and gives it a special key.
Additionally, all keys are now panic-less-ly converted to strings.

Fixup how odd numbers of args and non-string keys are handled to avoid runtime panics

---

interceptlogger.go
intlogger.go
logger.go
nulllogger.go

This PR is currently a proposal, and has not really undergone any
testing beyond "does it build" and "does go test pass".
While writing some middleware for logging gRPC requests in Nomad, I ran
into a situation where I want to log different response types at
different levels, and need to make those overridable by different
consumers in the middleware.
Ideally, this would be achieved with a lookup like so:
```go
func DefaultCodeToLevel(code codes.Code) logrus.Level {
switch code {
// Debug Logs
case codes.OK:
return hclog.Debug
case codes.Canceled:
return hclog.Debug
case codes.InvalidArgument:
return hclog.Debug
case codes.ResourceExhausted:
return hclog.Debug
case codes.FailedPrecondition:
return hclog.Debug
case codes.Aborted:
return hclog.Debug
case codes.OutOfRange:
return hclog.Debug …
```

Add a Log function for logging at a given level

---

intlogger.go
logger.go
logger_test.go
nulllogger.go

This can be used if you want to change the destination of your output
without application logic having to implement a second mutex to do so.

Adds ResetOutput and ResetOutputWithFlush

---

interceptlogger.go
interceptlogger_test.go
logger_test.go

Full disclosure: I'm pretty new to Go so it's possible this isn't the best solution.
Closes https://github.com/hashicorp/go-hclog/issues/61

Add OutputResettable conformance to InterceptLogger

---

intlogger.go
logger.go
logger_test.go

This has a number of use cases, chiefly allowing multiple related log
lines to be grouped together. It also reduces mutex contention in this
case.

This adds the ability for the caller to be responsible for locking

---

exclude.go
exclude_test.go
filter.go
intlogger.go
logger.go

When dealing with a package that logs too much, it can be desired to filter those log messages out. The only way to do that today is to implement a whole logger interface to hook into the proper point to filter them.
This instead adds a simple mechanism in intlogger to give the go/no-go on each log message before it's logged.

Provide a way to filter out log messages easily

---

intlogger.go

current regex is not compatible with go modules
```
testlog.go:34: 2020-06-01T12:02:21.198-0400 [DEBUG] go-hclog@v0.14.1-0.20200601160029-72283a822461/interceptlogger.go:62: podman.podmanHandle: Stopping exitWatcher: container=8e0151443072a743d06f6d059413410a0889cc850658b9414ad15d67e99784c0
testlog.go:34: 2020-06-01T12:02:21.198-0400 [DEBUG] go-hclog@v0.14.1-0.20200601160029-72283a822461/interceptlogger.go:62: podmanClient: Removing container: container=8e0151443072a743d06f6d059413410a0889cc850658b9414ad15d67e99784c0
testlog.go:34: 2020-06-01T12:02:25.325-0400 [WARN]  go-hclog@v0.14.1-0.20200601160029-72283a822461/interceptlogger.go:90: driver_harness.logmon: timed out waiting for read-side of process output pipe to close
```
Open to not using a regex as well :thinking:

gomod caller does not match regex

---

intlogger.go

...so that the next log entry occurs on its own line.

Make sure that we include a newline when writing stack traces

---

interceptlogger.go
interceptlogger_test.go
logger.go

From #50
When I first read over the `go-hclog` godoc I was a little confused about the distinction between the Logger and InterceptLogger. I think a big part of that confusion was the number of methods involved. This PR helps reduce that number by removing extra interface methods, and making the implementation of others more explicitly a wrapper for the underlying interface.

Remove extra intercept methods

---

logger.go
logger_test.go

Add an Off log level so that loggers can be easily disabled while
allowing other named loggers to use the same synchronized output.

add Level Off

---

interceptlogger.go
interceptlogger_test.go
intlogger.go
logger_test.go
stdlog_test.go

Builds on #76
This PR reduces the implementation of all the Logger methods in `interceptLogger` to call a single helper method.
It also makes two improvements to the `IncludeLocation` option:
1. remove the need to call `runtime.Caller` twice. This call is relatively expensive, and we were calling it twice for every log line. Instead of guessing at the offset we pass the offset along. The logger itself knows what offset to use.
2. fix a bug when `IncludeLocation` was used with `JSONFormat` and `InterceptLogger`. We were also using a fixed offset of 4, but that would be wrong when called from an InterceptLogger or an `intLogger` used as a sink.

Reduce intercept logger and fix a bug with json format and caller location

---

intlogger.go
logger_test.go

Plus tests for both the plain and JSON output.
Closes: #74
Signed-off-by: Marco Molteni <marco.molteni@mailbox.org>

fix: make JSON formatter respect the value of DisableTime

---

intlogger.go

fix https://github.com/hashicorp/go-hclog/issues/82 again.
Though #77 is related to #82, The problem was not fixed when I use intLoger.StandardLogger.
I had opened a PR for consul-esm to use hclog(https://github.com/hashicorp/consul-esm/pull/97).
It's depend on go-hclog(v0.15.0), which not include #77.
But my local use https://github.com/varnson/go-hclog/releases/tag/v0.15.5, which include #77, and I found the problem was not fixed.
Now I use https://github.com/varnson/go-hclog/releases/tag/v0.15.7 and it works well.

update callerOffset while use StandardWriter

---

intlogger.go
logger_test.go

fix: make JSON formatter respect the value of TimeFormat
Plus simplify the logic behind DisableTime
NOTE: This branch is off https://github.com/marco-m/go-hclog/tree/fix-disabletime and should be rebased on master once #75 is merged.

Cleanup timestamp logic

---

intlogger.go

This broke the API because things like go-plugin were using TimeFormat (as it was exported).

Change TimeFormatPlain back to TimeFormat

---

interceptlogger_test.go
intlogger.go
logger_test.go

This change improves 2 things:
1. empty strings are render as `""` instead of the absence of a value. The absence is fairly confusing.
2. Values that contain newlines are broken out and render under the key that they are for with indentation. This makes it possible to use tools like `spew.Sdump` easily on values and get easy to read output.
Here is an example the multiline rendering:
```
2021-02-13T15:22:31.131-0800 [INFO]  debug event detected event:
event=
| (*randomStruct)(0xc000284390)({
|  Count: (int) 1,
|  Max: (int) 1000,
|  File: (string) (len=7) "foo-bar"
| })
root="" num_buffers=10
more=
| ([]string) (len=40 cap=40) {
|  (string) (len=22) "TERM_PROGRAM=iTerm.app",
|  (string) (len=20) "TERM=screen-256color",
|  (string) (len=24) "SHELL=/usr/local/bin/zsh",
|  (string) (len=15) …
```

Improve rendering of empty strings and multiline values

---

intlogger.go
logger.go
logger_test.go
stdlog_test.go

Add the ability for wrappers of hclog to have the file and line number
point to their caller, instead of the wrappers, by specifying additional
offsets for the callstack when creating a logger.

Add an AdditionalLocationOffset option to LoggerOptions.

---

intlogger.go
logger.go
logger_test.go

Output from hashicorp/nomad#10858 using hclog v0.14.1 (double double quotes):
```
2021-07-06T10:06:01.590-0700 [WARN] ... task=redis health=critical output=""This is the output for state 2\n""
```
Output using hclog v0.16.1 (breaks naive 1-line-per-log parsers):
```
2021-07-06T15:41:34.112-0700 [WARN] ... task=redis health=warning
output=
| This is the output for state 1
```
Output using this PR:
```
2021-07-06T15:42:28.192-0700 [WARN] ... task=redis health=warning output="This is the output for state 1\n"
```

add Quote type to enable safe concise output of untrusted strings

---

intlogger.go
logger_loc_test.go
logger_test.go

These rules are more conservative that the current rules, effectively quoting a string value if any rune inside the string falls outside the inclusive range of `-` to `~`. This means spaces and quote marks of all kind, and all non Latin-1.
Fixes #98

Adjust the rules for deciding to quote a string value

---

intlogger.go
logger_test.go

Found that empty strings are being rendered as `foo="\"\"'`. Added `raw=true` to the special case for them and that appears to resolve the issue.  Added a test to capture the situation.

Set `raw=true` when special casing empty strings

---

README.md
interceptlogger.go
intlogger.go
logger.go
stdlog.go
stdlog_test.go

This PR adds a new option called `InferLevelsWithTimestamp` to the `StandardLoggerOptions` that allow ignoring timestamps from the beginning of log lines before attempting to infer log level.
Timestamp detection is done using a simple regular expression that looks for characters commonly found in timetamps, such as digits, `:`, `/` etc.
A new option was added to avoid modifying the existing `InferLevels` options. An alternative approach that I thought about was to add a `InferLevelsOptions` attribute to control how infer levels work that could a new `struct` or a bit mask:
```go
// As bit flags
appLogger.StandardWriter(&hclog.StandardLoggerOptions{
InferLevels: true,
InferLevelsOptions: hclog.IgnoreTimestamps
})
// As struct
appLogger.StandardWriter(&hclog.StandardLoggerOptions{ …
```

Add `InferLevelsWithTimestamp` option

---

colorize_unix.go
colorize_windows.go
intlogger.go
logger.go

This improves the readability of colored messages by only colorizing the level header rather than the whole message. On many terminals, some of the colors are hard to read for large segments of text. Colorizing just the header make it possible to easily visually scan the log output while preserving the readability of the log message itself.
Here is a random snippit showing the visual effect of this option:

Add ability to only colorize the header, not the whole log message

---

.github/workflows/test.yml

Looks like this didn't get updated whenever the master -> main switch happened.

fix GH test workflow after master -> main switch

---

go.mod
go.sum

Reference: https://github.com/advisories/GHSA-hp87-p4gw-j4gq
Reference: https://github.com/hashicorp/go-hclog/pull/112
Updates the github.com/stretchr/testify dependency, which in turn updates the gopkg.in/yaml.v3 dependency. Updated via:
```shell
go get github.com/stretchr/testify@v1.7.2
go mod tidy
```

deps: Update github.com/stretchr/testify@v1.7.2

---

intlogger.go
logger.go

This PR builds on https://github.com/hashicorp/go-hclog/pull/108, extending the ability to color fields as well as the level header.
When I have log lines with multiple fields (especially with long values), I find it hard to visually pinpoint the part of the log message I'm interested in. I think by dimming the `key=` part of the field, it'll be faster and easier to visually parse the information. For multi-line values, this will also dim the `|` prefix.
```go
log := hclog.New(&hclog.LoggerOptions{
Color:                hclog.AutoColor,
ColorHeaderAndFields: true,
})
```
> **Note**: if [`ColorHeaderOnly`](https://github.com/hashicorp/go-hclog/blob/2a06ec98d67e4c2de59fb4cc7916c14ffbb91be6/logger.go#L275) is _also_ set as `true`, that takes precedence.

Add `ColorHeaderAndFields` logger option

---

intlogger.go
logger_test.go

This also pulls over a specialized version of strconv.Quote for us to use.

When rendering multiple line output, still quote the individual lines

---

intlogger.go
logger.go
nulllogger.go

Useful introspection on a logger, to know what level it's at.

Add GetLevel to Logger interface

---

.github/workflows/test.yml
colorize_unix.go
colorize_windows.go
intlogger.go
logger.go

Cleanup AutoColor to make it never fail, instead do it's best to activate color if possible only.
Fixes #122

Improve AutoColor functionality

---

intlogger.go
logger.go

SubloggerHook is a function that when defined, is passed any new sublogger that is created. This allows hclog users to wrap any sublogger in similar functionality as the original, as well as adjust any sublogger parameters dynamically.

Add ability to wrap new subloggers

---

README.md
logger.go

This PR is a tiny docs update for the go doc around `InferLevelsWithTimestamp`.
The idea is to stop people running into a gotcha I experienced recently where `InferLevels` must be `true` in order for the `InferLevelsWithTimestamp` setting to have any impact.

Docs: InferLevelsWithTimestamp relies on InferLevels being true

---

intlogger.go
logger.go
logger_test.go

This implements the `SyncParentLevel` flag, which alters how Levels are propagated amongst sub-loggers. It's mutually exclusive with `IndependentLevels`.
When set, sub-loggers will take on the level of a direct parent/grandparent/etc and be unaffected by sibling sub-loggers changing their level.
This allows for more obvious hierarchies of sub-loggers to be created and used that share a common level.

Implement the ability to more logically share level hierarchies

---

intlogger.go
logger_test.go

Turns out that the color package we use was doing it's own "should
colors be on or not" detection, which interferred with our own
detection. This caused situations where colors were forced on to still
be off (and, maddeningly, would show up in weird contexts because it
dependent on Stdout being not a terminal to break when forced).
Fixes #127 
Closes #131

Fix colors not being forced on correctly.

---

hclogvet/go.mod
hclogvet/go.sum

fixes panic due to go1.22 incompats
```
==> Linting hclog statements...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x59351e]
goroutine 14 [running]:
go/types.(*Checker).handleBailout(0xc0004c9c00, 0xc0023f5c10)
/opt/google/go/src/go/types/check.go:367 +0x88
panic({0x70ef40?, 0x991a80?})
/opt/google/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0x7db790, 0x995620})
/opt/google/go/src/go/types/sizes.go:228 +0x31e
go/types.(*Config).sizeof(...)
/opt/google/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0x7db790?, 0x995620?})
/opt/google/go/src/go/types/const.go:76 +0x9e …
```

hclogvet: updates for go1.22

---

intlogger.go
logger.go
logger_test.go

To resolve #140 
This modification will not lead to some breaking change, because the attribute which added will default to false. If user want to use this feat, this attribute should be set to true.

support configure json escape when log in json format

---

.github/workflows/test.yml

Close GitHub Code Scanning Alert [#6](https://github.com/hashicorp/go-hclog/security/code-scanning/6).
Close SECVULN-22922.

pin actions/cache to v4.2.3

---

.github/dependabot.yaml
CHANGELOG.md

- As per the memo: https://go.hashi.co/memo/eng-004,
Enabling the dependabot for identifying and updating the security and version updates in the repositories rather handling it manually.
- Adding the CHANGELOG.md file to maintain standardisation across OSS core libraries.

IND-3810 enabling dependabot, changelog.md
